### ISSUE TITLE
Image scaling feature

### ISSUE THREAD

**Issue by PaulKnauseder** [migaku-official/Migaku-Editor-Addon#2]
Hey,
first of all, great addon, it makes editing a whole lot easier.
But i wanted to ask if there is a way to turn off the "Quick Image Resizing" because it shuts off other addons which affect images?
Thanks for your help!

**Comment by TowelSniffer** [comment]
yeah I have also had issues with this, I find it causes anki's check media to delete the images that have been affected.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
