### ISSUE TITLE
Conflict with cloze overlapper

### ISSUE THREAD

**Issue by ghost** [migaku-official/Migaku-Editor-Addon#3]
Here is the issue https://github.com/glutanimate/cloze-overlapper/issues/43

When a card is made using cloze overlapper the front is shown, but for the back the error "Invalid HTML on card: TypeError: Cannot read property 'innerHTML' of null" appears

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
